package generator

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	fp "path/filepath"
	"regexp"
	"runtime"
	"strings"

	"github.com/go-qamel/qamel/internal/config"
)

var (
	rxMakefile    = regexp.MustCompile(`^(\S+)\s*=\s*(.+)$`)
	rxCompilerVar = regexp.MustCompile(`\$\((\S+)\)`)
)

// CreateCgoFile creates cgo file in specified package,
// using cgo flags that generated by CreateCgoFlags().
func CreateCgoFile(profile config.Profile, projectDir string, pkgName string) error {
	// Make sure project directory is exists
	err := os.MkdirAll(projectDir, os.ModePerm)
	if err != nil {
		return err
	}

	// Get the package name
	if pkgName == "" {
		pkgName, err = getPackageNameFromDir(projectDir)
		if err != nil {
			return err
		}
	}

	// Create cgo flags
	cgoFlags, err := createCgoFlags(profile, projectDir)
	if err != nil {
		return fmt.Errorf("failed to create cgo flags: %v", err)
	}

	// Create destination file
	fileName := fp.Join(projectDir, "qamel-cgo-"+pkgName+".go")
	fileContent := fmt.Sprintln("package " + pkgName)
	fileContent += fmt.Sprintln()
	fileContent += fmt.Sprintln("/*")
	fileContent += fmt.Sprintln(cgoFlags)
	fileContent += fmt.Sprintln("*/")
	fileContent += fmt.Sprintln(`import "C"`)

	return saveToFile(fileName, fileContent)
}

// createCgoFlags creates cgo flags by using qmake
func createCgoFlags(profile config.Profile, projectDir string) (string, error) {
	// Create project file
	proContent := "QT += qml quick quickcontrols2 widgets svg\n"
	proContent += "CONFIG += release\n"
	if profile.OS == "windows" {
		proContent += "CONFIG += windows\n"
	}

	proFilePath := fp.Join(projectDir, "qamel.pro")
	err := saveToFile(proFilePath, proContent)
	if err != nil {
		return "", err
	}

	// Create makefile from project file using qmake
	makeFilePath := fp.Join(projectDir, "qamel.makefile")

	qmakeSpec := ""
	switch profile.OS {
	case "darwin":
		qmakeSpec = "macx-clang"
	case "linux":
		qmakeSpec = "linux-g++"
	case "windows":
		qmakeSpec = "win32-g++"
	}

	gccDir := fp.Dir(profile.Gcc)
	gxxDir := fp.Dir(profile.Gxx)
	envPath := os.Getenv("PATH")
	pathSeparator := ":"

	if runtime.GOOS == "windows" {
		pathSeparator = ";"
	}

	if fileExists(profile.Gcc) {
		envPath = fmt.Sprintf(`%s%s%s`, gccDir, pathSeparator, envPath)
	}

	if fileExists(profile.Gxx) && gxxDir != gccDir {
		envPath = fmt.Sprintf(`%s%s%s`, gxxDir, pathSeparator, envPath)
	}

	cmdQmake := exec.Command(profile.Qmake, "-o", makeFilePath, "-spec", qmakeSpec, proFilePath)
	cmdQmake.Dir = projectDir
	cmdQmake.Env = append(os.Environ(), "PATH="+envPath)
	if btOutput, err := cmdQmake.CombinedOutput(); err != nil {
		return "", fmt.Errorf("%v\n%s", err, btOutput)
	}

	// Parse makefile
	qmakeResultPath := makeFilePath
	if profile.OS == "windows" {
		qmakeResultPath += ".Release"
	}

	mapCompiler := map[string]string{}
	makeFile, err := os.Open(qmakeResultPath)
	if err != nil {
		return "", err
	}
	defer makeFile.Close()

	scanner := bufio.NewScanner(makeFile)
	for scanner.Scan() {
		text := scanner.Text()
		parts := rxMakefile.FindStringSubmatch(text)
		if len(parts) != 3 {
			continue
		}

		mapCompiler[parts[1]] = parts[2]
	}

	if err := scanner.Err(); err != nil {
		return "", err
	}

    if _, ok := mapCompiler["EXPORT_ARCH_ARGS"]; ok {
        if profile.Arch == "amd64" {
            mapCompiler["EXPORT_ARCH_ARGS"] = "-arch x86_64"
        } else if profile.Arch == "arm64" {
            mapCompiler["EXPORT_ARCH_ARGS"] = "-arch aarch64"
        } else {
            mapCompiler["EXPORT_ARCH_ARGS"] = "-arch i386"
        }
    }
    delete(mapCompiler, "EXPORT_ACTIVE_ARCHS")

	// Convert variable in compiler flags
	for flagKey, flagValue := range mapCompiler {
		variables := rxCompilerVar.FindAllString(flagValue, -1)
		for _, variable := range variables {
			variableKey := rxCompilerVar.ReplaceAllString(variable, "$1")
			variableValue := mapCompiler[variableKey]
			flagValue = strings.Replace(flagValue, variable, variableValue, -1)
		}

		// Go does not support big-obj files yet (see https://github.com/golang/go/issues/24341).
		// However, qmake in mingw64 uses them by default. To bypass it, we need to remove `-Wa,-mbig-obj` flags.
		flagValue = strings.Replace(flagValue, " -Wa,-mbig-obj ", " ", -1)
		mapCompiler[flagKey] = strings.TrimSpace(flagValue)
	}

	// Fetch the needed flags for cgo
	cgoFlags := fmt.Sprintf("#cgo CFLAGS: %s\n", mapCompiler["CFLAGS"])
	cgoFlags += fmt.Sprintf("#cgo CXXFLAGS: %s\n", mapCompiler["CXXFLAGS"])
	cgoFlags += fmt.Sprintf("#cgo CXXFLAGS: %s\n", mapCompiler["INCPATH"])
	cgoFlags += fmt.Sprintf("#cgo LDFLAGS: %s\n", mapCompiler["LFLAGS"])
	cgoFlags += fmt.Sprintf("#cgo LDFLAGS: %s\n", mapCompiler["LIBS"])
	cgoFlags += fmt.Sprintln("#cgo CFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type")
	cgoFlags += fmt.Sprint("#cgo CXXFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type")

	// Remove generated file and folder
	os.Remove(proFilePath)
	os.Remove(makeFilePath)
	os.Remove(makeFilePath + ".Debug")
	os.Remove(makeFilePath + ".Release")
	os.Remove(fp.Join(projectDir, ".qmake.stash"))

	debugDir := fp.Join(projectDir, "debug")
	if dirExists(debugDir) && dirEmpty(debugDir) {
		os.RemoveAll(debugDir)
	}

	releaseDir := fp.Join(projectDir, "release")
	if dirExists(releaseDir) && dirEmpty(releaseDir) {
		os.RemoveAll(releaseDir)
	}

	return cgoFlags, nil
}
